# Generated by Django 4.2.8 on 2024-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productNo", models.IntegerField()),
                ("productName", models.CharField(max_length=255)),
                ("productUnit", models.CharField(max_length=50)),
                ("productPrice", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
