# Generated by Django 4.2.8 on 2024-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monthly_closing", "0002_remove_product_id_alter_product_productno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productNo",
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
