# Generated by Django 4.2.8 on 2024-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monthly_closing", "0003_alter_product_productno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productNo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
